### ISSUE TITLE
Percent increase in air pollutants around Austin

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/bleed-orange-measure-purple#12]
# Percent Increase in Air Pollution
An interesting metric to look at would involve looking at how concentrations have decreased since the shelter-in-place order in Austin. One metric to accomplish this would be percent increase (although hopefully it is negative) during the shutdown period. 

## Problem
Since air pollution has seasonal trends, we cannot set a baseline using data from the beginning of the year to now so we must establish a baseline using a different method.

## Solution
Using historic data from the period of Feb. 1 - May 1 for the important pollutants (see below) to develop the baseline. 
- [x] Use at most 5 years of historic data or whatever is available from the EPA/TCEQ monitoring sites.
- [x] Average these concentration profiles and use the average values as the baseline to compare this year's measurements too. 

Create two figures: 

- [x] the individual traces for each year using a low alpha value for the past year and a darker alpha for the average value and 2020 concentration profile
- [x] the percent increase in concentration for each pollutant

## Pollutants
These are the main pollutants to consider:
- PM2.5 mass concentration
- PM1 number concentration (if possible)
- NO2 concentration
- O3 concentration

**Comment by HagenFritz** [comment]
The layout/format for this plot should essentially look like that described in this [issue](https://github.com/intelligent-environments-lab/bleed-orange-measure-purple/issues/20) but instead of concentration on the y-axis, it should be percent change.

**Comment by calvinjlin** [comment]
With the exception of the average value line, this issue is considered completed, and the relevant figure was submitted to the covid repo last week.
