### ISSUE TITLE
Air pollution mean comparison plot

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/bleed-orange-measure-purple#20]
# COVID19 Air Pollution Mean Comparison Plot
This plot should give a nice overview of the differences in concentration across multiple years.

The format of the figure should be:
- subplot with 3 rows and 1 column
- each plot represents a pollutant: pm2.5, no2, and o3
- y-axis should be concentration (in relevant units)
- x-axis should be shared for the column (```sharey='col'```) and in a date format from Feb 1st to May 1 that does NOT include year but just the month name (see [mdates](https://matplotlib.org/3.2.1/api/dates_api.html))
- plot traces for up to five years in the past with a lower alpha (~0.7) and color-coded
- plot the 2020 trace with an alpha=1 and a thicker linewidth

**Comment by calvinjlin** [comment]
Completed last week, figure was committed to covid19 project
